---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: argocd-internal-transport
  namespace: argocd
spec:
  serverName: argocd-server.argocd.svc.cluster.local
  rootCAsSecrets:
    - internal-ca
  insecureSkipVerify: false
