infra_admin_username: "default-admin"
infra_admin_password_hash: "$6$rounds=656000$yoursalt$yourhashedpasswordhere"
ansible_user: "{{ infra_admin_username }}"
ansible_port: 22
timezone: "Europe/Zurich"
motd_message_url: "https://github.com/mtnstar/infra"
