---
- name: Install base packages
  package:
    name:
      - netplan.io
      - curl
      - vim
      - python3-pip
      - net-tools
      - ssh
      - cron
      - dnsutils
    state: present

- name:  Ensure cron service is running
  ansible.builtin.systemd:
    name: cron
    state: started
    enabled: yes
  become: yes

- name: Ensure unattended-upgrades is installed
  apt:
    name: unattended-upgrades
    state: present

- name: Ensure automatic updates are enabled
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    owner: root
    group: root
    mode: "0644"

- name: Ensure unattended-upgrades service is enabled and running
  systemd:
    name: unattended-upgrades.service
    enabled: true
    state: started

- name: Force a reload of unattended-upgrades configuration
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
  changed_when: false
