---
- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present

- name: Ensure PermitRootLogin is set to no
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    backup: true
  notify: Restart sshd

- name: Configure sshd port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Port"
    line: "Port {{ sshd_port }}"
    state: present
    backup: true
  notify: Restart sshd

- name: Lock root account password
  ansible.builtin.user:
    name: root
    password_lock: true
