name: Molecule CI

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start podman service
        run: |
          podman --version
          systemctl --user start podman.socket

      - name: Run molecule
        run: |
          podman run --rm \
            -v "${{ github.workspace }}":/work \
            -w /work \
            -v "/var/run/user/$(id -u)/podman/podman.sock:/var/run/user/1000/podman/podman.sock" \
            -v "${{ github.workspace }}/molecule/.ansible_vault_pass.txt":/home/mtn-admin/.ansible_vault_pass.txt:ro \
            --userns=keep-id:uid="$(id -u)",gid="$(id -g)" \
            ghcr.io/mtnstar/mtn-shell:latest \
            sh -c 'id && ls -lah /home/mtn-admin && cd /work && molecule test -s linux_base'
